language: java

before_install:
    - sudo apt-get update
    - sudo apt-get install groovy
sudo: required
install: true
script: mvn clean package -DskipTests=true
sudo: required
jdk:
  - oraclejdk9
notifications:
  email: false
